//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagories_type_to_event
    {
        public int catagories_type_to_event_code { get; set; }
        public Nullable<int> event_code { get; set; }
        public string dis { get; set; }
    }
}
