//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Guests = new HashSet<Guests>();
        }
    
        public int event_code { get; set; }
        public Nullable<int> event_type { get; set; }
        public string event_dis { get; set; }
        public System.DateTime event_date { get; set; }
        public Nullable<int> manager_code { get; set; }
        public Nullable<int> seating_arrangement_code { get; set; }
        public string invitation { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual SeatingArrangement SeatingArrangement { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guests> Guests { get; set; }
    }
}
