//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        public int guest_code { get; set; }
        public string guest_name { get; set; }
        public string guest_link_email { get; set; }
        public Nullable<int> event_code { get; set; }
        public string gender { get; set; }
        public string table_code { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
