//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest_table_members
    {
        public int table_members_code { get; set; }
        public Nullable<int> guest_code { get; set; }
        public Nullable<int> friend1_code { get; set; }
        public Nullable<int> friend2_code { get; set; }
        public Nullable<int> friend3_code { get; set; }
        public Nullable<int> dislike_code { get; set; }
    }
}
