//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.guest_table_member = new HashSet<guest_table_member>();
            this.Guest_table = new HashSet<Guest_table>();
            this.guest_table_member1 = new HashSet<guest_table_member>();
        }
    
        public int guest_id { get; set; }
        public string guest_first_name { get; set; }
        public string guest_last_name { get; set; }
        public string guest_tz { get; set; }
        public string guest_email { get; set; }
        public Nullable<int> event_id { get; set; }
        public string gender { get; set; }
        public Nullable<int> table_id { get; set; }
        public string guest_message_befor { get; set; }
        public string guest_message_after { get; set; }
        public Nullable<int> guest_catagory_id { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Guest_catagory Guest_catagory { get; set; }
        public virtual Tables Tables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guest_table_member> guest_table_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest_table> Guest_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guest_table_member> guest_table_member1 { get; set; }
    }
}
