//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest_table_member
    {
        public int table_members_id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> friend_id { get; set; }
        public Nullable<bool> like_or_not { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Guest Guest1 { get; set; }
    }
}
