//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YourPlaceEntities : DbContext
    {
        public YourPlaceEntities()
            : base("name=YourPlaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catagories_type_to_event> Catagories_type_to_event { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Guests_catagories_guests> Guests_catagories_guests { get; set; }
        public virtual DbSet<Guests_table> Guests_table { get; set; }
        public virtual DbSet<SeatingArrangement> SeatingArrangement { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_category> Table_category { get; set; }
        public virtual DbSet<Tables> Tables { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<guest_table_members> guest_table_members { get; set; }
    }
}
